name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~ /.ssh
        echo "$SSH_PRIVATE_KEY" > ~ /root/.ssh/id_rsa
        chmod 600 ~ /root/.ssh/id_rsa
        chmod 755 ~ /root/.ssh/id_rsa
        
        ssh -i /root/.ssh/my_new_key root@143.244.171.220
          cd /home/dev/Turing.edu.az || exit
          git pull origin main || exit
          npm install || exit
          pm2 restart your-app-name || exit
        EOF
